### ISSUE TITLE
Question: how to create a timer

### ISSUE THREAD

**Issue by nathansamson** [smart-leds-rs/ws2812-timer-delay-rs#4]
Hi

I want to use this project but I am having trouble setting this up. I am using this in combination with the arduino-hal project (which I assume is possible?)

I am just unsure how to initialize the timer for this implementation.

https://gist.github.com/nathansamson/362fb2dd32413a0f741d00817665f5ad

Note: I am creating an issue as I am not sure if there a proper support forum for this, thanks for steering me in the right direction

Note: I previously had a quick setup with the "normal" arduino tooling using this tutorial (https://howtomechatronics.com/tutorials/arduino/how-to-control-ws2812b-individually-addressable-leds-using-arduino/) but I want to use rust for this project.

**Comment by sajattack** [comment]
I would recommend checking with the folks behind avr-hal and seeing if they have an implementation of embedded_hal::timer::Countdown. I'm not sure where their chatroom is but the repo is here https://github.com/Rahix/avr-hal

**Comment by david-sawatzke** [comment]
I'm pretty sure the usual AVRs with a 20 MHz clock are too slow for this backend. Some time ago I implemented this example for using smart-leds with AVRs: https://github.com/smart-leds-rs/smart-leds-samples/tree/master/avr-examples/examples based on ws2812-spi-rs and preprocessing the data.

It's currently probably your best bet.
